### ISSUE TITLE
Set signup to redirect to edit their profile. 

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#89] opened 2013-02-12 04:32 UTC
Also, github users need to pick a username at this point. It might make sense to move that field off of sign up all together and put it on the edit profile page.

**Comment by StacyJCarlos** [comment] 2013-02-12 06:50
Do we want to wait for e-mail confirmation before creating user accounts or will they be made automatically? I know many people don't like having to confirm their accounts, but if we make them automatically, people may have accounts made under the wrong e-mail because of a mistype. What does everyone think?

**Comment by nickserv** [comment] 2013-02-13 02:48
That's a good question. It seems like a good practice is to nag users to confirm their account via email right after account creation (so accounts aren't sitting around that are hooked up to invalid email addresses). We might want to let users partially use their new accounts before email confirmation, but that would probably take a bit more backend work in terms of permissions.

**Comment by StacyJCarlos** [comment] 2013-02-13 02:58
Personally, I think we should not allow any permissions without email confirmation. What do you guys think?

**Comment by nickserv** [comment] 2013-02-13 03:00
So, accounts would have the same permissions as accountles users (read all only) before the email address is confirmed?

**Comment by StacyJCarlos** [comment] 2013-02-13 03:03
@thenickperson  Essentially, yes

**Comment by nickserv** [comment] 2013-02-13 04:15
It seems like we're agreeing on locking write access until email addresses are verified. I'll make a separate issue for that.

**Comment by nickserv** [comment] 2013-02-13 06:38
Please don't close this yet, we still need to do the signup redirect.

**Closed as completed** 2013-02-16 00:49 UTC
Labels: enhancement
