### ISSUE TITLE
Reach 100% test coverage

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#231] opened 2013-07-08 14:21 UTC

**Comment by kristenmills** [comment] 2013-07-08 15:34
Duplicate of #124 which we closed because we can't actually reach 100% and did the best that we can. I think it was some helper methods used by devise. Don't remember and I'm not in front of my computer. So I say this issue should be closed as well. Everyone should just test as they go and our coverage will stay relatively high. There might be some things that need to be added to the tests but this shouldn't be a goal for us.

**Comment by toroidal-code** [comment] 2013-10-02 17:47
won't fix, unnecessary.

**Closed as completed by toroidal-code** 2013-10-02 17:47 UTC
Labels: enhancement, wontfix
